-- Drop the table if it already exists to ensure a clean setup
DROP TABLE IF EXISTS churn_features;

-- Create the table with a well-defined schema
-- This schema is designed to hold the transformed features for the churn model.
CREATE TABLE churn_features (
    "customerID" TEXT PRIMARY KEY,
    "gender" INTEGER,
    "SeniorCitizen" INTEGER,
    "Partner" INTEGER,
    "Dependents" INTEGER,
    "tenure" REAL,
    "PhoneService" INTEGER,
    "PaperlessBilling" INTEGER,
    "MonthlyCharges" REAL,
    "TotalCharges" REAL,
    "Churn" INTEGER,
    "total_interactions" REAL,
    "days_since_last_interaction" REAL,
    "billing_inquiry" REAL,
    "complaint" REAL,
    "service_upgrade" REAL,
    "support_call" REAL,
    "website_visit" REAL,
    "MultipleLines_No phone service" INTEGER,
    "MultipleLines_Yes" INTEGER,
    "InternetService_Fiber optic" INTEGER,
    "InternetService_No" INTEGER,
    "OnlineSecurity_No internet service" INTEGER,
    "OnlineSecurity_Yes" INTEGER,
    "OnlineBackup_No internet service" INTEGER,
    "OnlineBackup_Yes" INTEGER,
    "DeviceProtection_No internet service" INTEGER,
    "DeviceProtection_Yes" INTEGER,
    "TechSupport_No internet service" INTEGER,
    "TechSupport_Yes" INTEGER,
    "StreamingTV_No internet service" INTEGER,
    "StreamingTV_Yes" INTEGER,
    "StreamingMovies_No internet service" INTEGER,
    "StreamingMovies_Yes" INTEGER,
    "Contract_One year" INTEGER,
    "Contract_Two year" INTEGER,
    "PaymentMethod_Credit card (automatic)" INTEGER,
    "PaymentMethod_Electronic check" INTEGER,
    "PaymentMethod_Mailed check" INTEGER,
    "TenureInYears" REAL,
    "NumAdditionalServices" REAL,
    "MonthlyTenureRatio" REAL
);